# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flixPartOne' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flixPartOne
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.3'

  target 'flixPartOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flixPartOneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
